services:
  publisherdb:
    container_name: botscrewdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: botscrewdb
    extends:
      file: common-config.yaml
      service: microservice-postgres-config
  task:
    image: "victortarasov/test_task:v1"
    container_name: test_task-ms
    extends:
      file: common-config.yaml
      service: microservice-base-config
networks:
  botscrew:
    driver: "bridge"
    external: true